## 05. 이미지 조정

In [5]:
import cv2
import numpy as np


In [6]:
import cv2
import numpy as np

DOG_PATH = "images/dog.jpg"


### 5-1. 이미지 복사

In [7]:
img = cv2.imread(DOG_PATH)
shallow_copy = img
deep_copy = img.copy()

gray = cv2.cvtColor(shallow_copy, cv2.COLOR_BGR2GRAY)

cv2.imshow("original", img)
cv2.imshow("shallow", shallow_copy)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 5-2. 리사이즈

In [8]:
img = cv2.imread(DOG_PATH)
# img.shape

# 고정 크기를 입력해서 조정
# dst = cv2.resize(img, (213,320))

# 비율로 조정
dst = cv2.resize(img, None, fx=2.5, fy=2.5, interpolation=cv2.INTER_LINEAR)
cubic = cv2.resize(img, None, fx=2.5, fy=2.5, interpolation=cv2.INTER_CUBIC)

cv2.imshow("dst", dst)
cv2.imshow("cubic", cubic)
cv2.waitKey(0)
cv2.destroyAllWindows()

### 실습2. 영상 리사이즈 해서 출력


In [9]:
import cv2

FIRE_VIDEO_PATH = "videos/fire.mp4"
cap = cv2.VideoCapture(FIRE_VIDEO_PATH)

while cap.isOpened(): 
    ret, frame = cap.read()

    if not ret:
        break

    resized_frame = cv2.resize(frame, None, fx=0.5, fy=0.5)

    cv2.imshow("Resize_Video", resized_frame) 

    if cv2.waitKey(60) == ord("q"):
        break
    
cap.release()
cv2.destroyAllWindows()


In [10]:
img = cv2.imread(DOG_PATH)

size_up = cv2.pyrUp(img)
size_down = cv2.pyrDown(img)

cv2.imshow("Pyr up", size_up)
cv2.imshow("origin", img)
cv2.imshow("Pyr Down", size_down)
cv2.waitKey(0)
cv2.destroyAllWindows()



### 5-3. 이미지 자르기

In [11]:
img = cv2.imread(DOG_PATH)
# print(img.shape)
cropped = img[100:180, 200:270]

cv2.imshow("Dog", img)
cv2.imshow("Dog cropped", cropped)

cv2.waitKey(0)
cv2.destroyAllWindows()



In [12]:
img = cv2.imread(DOG_PATH)

cropped = img[100:180, 200:270]
img[100:180, 190:260] = cropped


cv2.imshow("Dog", img)
cv2.imshow("Dog cropped", cropped)

cv2.waitKey(0)
cv2.destroyAllWindows()


### 5-4 이미지 대칭
- 'flipcode > 0' : 좌우 반전(y축 반전)
- 'flipcode == 0' : 상하 반전(x축 반전)
- 'flipcode < 0' : 상하좌우 반전

In [13]:
img = cv2.imcount(DOG_PATH)

dst_1 = cv2.flip(img, 1)
dst_2 = cv2.flip(img, 0)
dst_3 = cv2.flip(img, -1)

cv2.imshow("img", img)
cv2.imshow("dst_1", dst_1)
cv2.imshow("dst_1", dst_2)
cv2.imshow("dst_1", dst_3)


cv2.waitKey()
cv2.destroyAllWindows()

### 실습3. 이미지 조정


In [14]:
import cv2

# 이미지 경로 설정
IMAGE_PATH = "images/hanni.jpg"  # 여기에 이미지 파일 경로를 입력하세요

# 이미지 읽기
img = cv2.imread(IMAGE_PATH)

# 이미지 크기 축소 (가로, 세로 1/2)
img2 = cv2.resize(img, None, fx=0.5, fy=0.5)

# 축소된 이미지 좌우 반전
img3 = cv2.flip(img2, 1)

# 원본 이미지에 반전된 이미지 삽입
img[img.shape[0] - img3.shape[0]:img.shape[0], img.shape[1] - img3.shape[1]:img.shape[1]] = img3

# 결과 출력
cv2.imshow("Result", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [15]:
import cv2

IMAGE_PATH = "images/hanni.jpg"

dst = cv2.pyrDown(img)
dst = cv2.flip(dst,1)

iheight, iwidth, ichannel = img.shape
dheight, dwidth, dchannel = dst.shape

img[iheight-dheight:iheight, iwidth-dwidth:iwidth] = dst

cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [16]:
img = cv2.imread(IMAGE_PATH)

blue, green, red = cv2.split(img)
print(blue, green, red)

cv2.imshow("Blue", blue)
cv2.imshow("Green", green)
cv2.imshow("Red", red)

cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 9 37 51 ... 49 49 48]
 [14 41 54 ... 49 49 48]
 [20 46 58 ... 49 49 48]
 ...
 [21 40 49 ... 36 33 32]
 [20 40 49 ... 37 33 33]
 [19 35 47 ... 42 35 34]] [[12 40 53 ... 55 55 53]
 [17 44 56 ... 55 55 53]
 [23 49 60 ... 55 55 53]
 ...
 [21 40 48 ... 40 37 39]
 [20 40 48 ... 41 37 40]
 [22 38 49 ... 46 39 41]] [[17 45 61 ... 62 62 62]
 [22 49 64 ... 62 62 62]
 [28 54 68 ... 62 62 62]
 ...
 [27 46 57 ... 58 55 56]
 [26 46 57 ... 59 55 57]
 [27 43 57 ... 64 57 58]]


In [17]:
img = cv2.imread(IMAGE_PATH)

blue, green, red = cv2.split(img)
merged_image = cv2.merge([blue,green,red])
cv2.imshow("merged", merged_image)

cv2.waitKey(0)
cv2.destroyAllWindows()

### 5-4. 이미지 색상 변경

In [18]:
import cv2

img = cv2.imread(IMAGE_PATH)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

cv2.imshow("gray", gray)
cv2.imshow("rgb", rgb)

cv2.waitKey(0)
cv2.destroyAllWindows()




### 실습4. 이미지 흑백 반전

In [19]:
import cv2

img = cv2.imread(IMAGE_PATH, cv2.IMREAD_GRAYSCALE)

inverted = 255 - img

cv2.imshow("Ori", img)
cv2.imshow("Inv", inverted)q
cv2.waitKey(0)
cv2.destroyAllWindows()


SyntaxError: invalid syntax (934773151.py, line 8)

### 5-5 이미지 흐리기(GaussianBlur)

In [20]:
img = cv2.imread(IMAGE_PATH)

# 커널을 사용하는 방식
# (3,3) (5,5) (7,7)을 주로 사용
kernel_3 = cv2.GaussianBlur(img, (3,3), 0)
kernel_5 = cv2.GaussianBlur(img, (5,5), 0)
kernel_7 = cv2.GaussianBlur(img, (7,7), 0)

cv2.imshow("kernel_3", kernel_3)
cv2.imshow("kernel_5", kernel_5)
cv2.imshow("kernel_7", kernel_7)

cv2.waitKey(0)
cv2.destroyAllWindows()



In [21]:
import cv2

img = cv2.imread(IMAGE_PATH)

# 표준편차를 사용하는 방식

sigma_3 = cv2.GaussianBlur(img, (0,0), 1)
sigma_5 = cv2.GaussianBlur(img, (0,0), 2)
sigma_7 = cv2.GaussianBlur(img, (0,0), 3)

cv2.imshow("sigma_3", sigma_3)
cv2.imshow("sigma_5", sigma_5)
cv2.imshow("sigma_7", sigma_7)

cv2.waitKey(0)
cv2.destroyAllWindows()



### 5-6. 이미지 회전
- rotateCode
 - 'cv2.ROTATE_90_CLOCKWISE' : 시계방향 90도 회전
 - 'cv2.ROTATE_180' : 180도 회전
 - 'cv2.ROTATE_90_COUNTERCLOCKWISE' : 반시계방향 90도 회전


In [22]:
import cv2

img = cv2.imread(IMAGE_PATH)

dst_90 = cv2.rotate(img,cv2.ROTATE_90_CLOCKWISE)
dst_180 = cv2.rotate(img,cv2.ROTATE_180)
dst_90_counter = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)

cv2.imshow("dst_90", dst_90)
cv2.imshow("dst_180", dst_180)
cv2.imshow("dst_90_counter", dst_90_counter)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
# affine 변환 사용

import cv2
import numpy as np
import math

img = cv2.imread("IMAGE_PATH")
rad = 20 * math.pi / 180 
affine = np.array([[math.cos(rad), -math.sin(rad), 0],[math.sin(rad), math.cos(rad), 0]], dtype=np.float32)
dst = cv2.warpAffine(img, affine, (img.shape[1], img.shape[0]))
cv2.imshow("rotate", dst)
cv2.waitKey(0)
cv2.destroyAllWindows()


### 복습

In [3]:
import cv2
import numpy as np

In [1]:
import cv2
import numpy as np
img = np.zeros((400,600,3), dtype=np.uint8)
img[100:200, 300:400] =  (255,255,255)
cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyWindow()

TypeError: destroyWindow() missing required argument 'winname' (pos 1)

In [2]:
img = np.zeros((400,600,3), dtype=np.uint8)
cv2.line(img, (100,100),(300,300), (255,0,0), 5, cv2.LINE_AA)
cv2.circle(img, (200,300), 50, (0,255,0), cv2.FILLED)
cv2.rectangle(img,(150,150), (250,250), (0,0,255), 10)

cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyWindow()

TypeError: destroyWindow() missing required argument 'winname' (pos 1)

In [3]:
img = np.zeros((400,600,3), dtype=np.uint8)
cv2.putText(img, "Hello world", (50,50), cv2.FONT_HERSHEY_TRIPLEX | cv2.FONT_ITALIC, 2, (255,255,0), 2)

cv2.imshow("img", img)
cv2.waitKey(0)
cv2.destroyWindow()

TypeError: destroyWindow() missing required argument 'winname' (pos 1)

In [ ]:
img = cv2.imread("images/hanni.jpg")
dst = cv2.resize(img, None, fx=1.5, fy=1.5)

cv2.imshow("img", dst)
cv2.waitKey(0)
cv2.destroyWindow()

TypeError: destroyWindow() missing required argument 'winname' (pos 1)

: 

In [4]:
import cv2
import numpy as np
img = cv2.imread("images/hanni.jpg")

affine = cv2.getRotationMatrix2D((img.shape[1]/2, img.shape[0]/2), -60, 1)
cv2.warpAffine(img, affine, (img.shape[1], img.shape[0]))

cv2.imshow("img", dst)
cv2.waitKey(0)
cv2.destroyWindow()

NameError: name 'dst' is not defined